fabric:
  walletPath: wallet
  connectionConfig: ./connection.yaml
  caIpPort: http://192.168.56.127:7054
  caCertPath: ./ca.orgbrcoin.com-cert.pem
  caEnrollId: admin
  caEnrollPw: adminpw
  mspId: brcoinMSP
  channelName: brcoin-channel
  chaincodeName: brcoin-cc

server:
    port: 8081
#logging:
#  level:
#    root: debug
  
#batch:
#
#    job:
#
#      enabled: false